### ISSUE TITLE
task 10 failed - "invalid 'times' argument"

### ISSUE THREAD

**Issue by nbutyrate** [lch14forever/BEEM-static#3]
hi here is my workflow

fungi <- read.table("Normal.txt", sep="\t", row.names=1, header=T)

res_2 <- func.EM(m, ncpu=4)

and following is the error

############# Run for iteration 1: #############
E-step: estimating scaled parameters...
Error in { : task 10 failed - "invalid 'times' argument"

attached i s the input file

please help me solve this

[Normal.txt](https://github.com/lch14forever/BEEM-static/files/3918450/Normal.txt)

**Comment by lch14forever** [comment]
Hi

I am not sure what `m` is. But in your input data, there are rows with only one non-zero entry, which is insufficient for the inference.

You can remove rows (taxa) with low abundance in many samples, and I have implemented an assertion to check this in the latest commit. 

In addition, I think 36 samples might not be enough for accurate BEEM-static analysis.

Chenhao

**Comment by lch14forever** [comment]
Feel free to reopen if it doesn't solve the problem.
